language: python
python:
  - "2.7"
  # The following seems to have a problem with pip..
  #- "3.2"
env:
  - SB_PIPE=$(pwd)
# necessary for installing Python dependencies
#virtualenv:
#  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo add-apt-repository ppa:texlive-backports/ppa -y
  - sudo apt-get update -q
  - sudo apt-get -y --force-yes install r-base r-base-dev r-cran-abind r-cran-ggplot2
  - sudo apt-get -y --force-yes --no-install-recommends install texlive-latex-base texlive-latex-recommended
install:
  # install other dependencies
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
#  - nosetests -v --with-coverage --cover-tests --cover-package=noseselecttests noseselecttests/tests.py
  - wget https://github.com/copasi/COPASI/releases/download/Build-104/COPASI-4.16.104-Linux-64bit.tar.gz
  - tar xvzf COPASI-4.16.104-Linux-64bit.tar.gz
  - PATH=$PATH:COPASI-4.16.104-Linux-64bit/bin/
  - CopasiSE
#  Use nosetests so that travis output depends on the return value from the test_suite 
#  - nosetests --tests=tests/test_suite.py
  - python tests/test_suite.py
