language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
addons:
    code_climate:
        repo_token: 72d60e73895e6f04c7495a2c965dc8b1cc215f0406e2672e007d362195edd7db
install:
  # install dependencies
  - pip install -r requirements.txt
  - export SB_PIPE="${HOME}/pdp10/sb_pipe"
  - export PATH=$PATH:${SB_PIPE}
  - python setup.py install
# command to run tests
script:
  - echo "Skipping nosetests for now"
#  - nosetests -v --with-coverage --cover-tests --cover-package=noseselecttests noseselecttests/tests.py
#  - nosetests -v tests/ins_rec_model/Working_Folder/test_insulin_receptor.py
# It would be nicer to run the tests_suite directly..
