language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# necessary for installing Python dependencies
#virtualenv:
#  system_site_packages: true
before_install:
## NEED TO ADD COPASI TOO..
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
#okay! :-)
#  - sudo add-apt-repository ppa:marutter/rrutter -y
#  - sudo add-apt-repository ppa:texlive-backports/ppa -y
#  - sudo apt-get update -q
#  - sudo apt-get -y --force-yes install python-pp python-scipy python-numpy
#  - sudo apt-get -y --force-yes install r-base r-base-dev r-cran-abind r-cran-stringr 
#  - sudo apt-get -y --force-yes --no-install-recommends install texlive-latex-base texlive-latex-recommended
install:
  # install other dependencies
#  - pip install -r requirements.txt
  - export SB_PIPE="${HOME}/pdp10/sb_pipe"
  - python setup.py install
# command to run tests
script:
#  - nosetests -v --with-coverage --cover-tests --cover-package=noseselecttests noseselecttests/tests.py
  - export SB_PIPE="${HOME}/pdp10/sb_pipe"
#  The following works locally, but eventually there is an error message reporting that the configuration files don't exist
#  - nosetests --tests=tests/test_suite.py
#  The following works locally with no error message
# - python tests/test_suite.py

