language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
#  - SB_PIPE="${HOME}/sb_pipe"
  - SB_PIPE=$(pwd)    
# necessary for installing Python dependencies
#virtualenv:
#  system_site_packages: true
before_install:
  ## Install Copasi
  - wget https://github.com/copasi/COPASI/releases/download/Build-104/COPASI-4.16.104-Linux-64bit.tar.gz
  - tar xvzf COPASI-4.16.104-Linux-64bit.tar.gz
  - export PATH=$PATH:/COPASI-4.16.104-Linux-64bit/bin/
  # Not sure if the following is needed
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo add-apt-repository ppa:texlive-backports/ppa -y
  - sudo apt-get update -q
  #- sudo apt-get -y --force-yes install python-pp
  - sudo apt-get -y --force-yes install r-base r-base-dev r-cran-abind r-cran-stringr 
  - sudo apt-get -y --force-yes --no-install-recommends install texlive-latex-base texlive-latex-recommended
install:
  # install other dependencies
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
#  - nosetests -v --with-coverage --cover-tests --cover-package=noseselecttests noseselecttests/tests.py
#  The following works locally, but eventually there is an error message reporting that the configuration files don't exist
#  - nosetests --tests=tests/test_suite.py
#  The following works locally with no error message
#  In Travis-CI: 
#File "tests/test_suite.py", line 38, in <module>
#    from test_ir_simulate import TestIRSimulate
#ImportError: No module named test_ir_simulate
  - python tests/test_suite.py
#  - python tests/insulin_receptor/Working_Folder/test_ir_lsf.py
#  - python tests/insulin_receptor/Working_Folder/test_ir_param_estim.py
#  - python tests/insulin_receptor/Working_Folder/test_ir_param_scan.py
#  - python tests/insulin_receptor/Working_Folder/test_ir_sensitivity.py
#  - python tests/insulin_receptor/Working_Folder/test_ir_sge.py
#  - python tests/insulin_receptor/Working_Folder/test_ir_simulate.py
