language: python
# NOTE: 14.04 uses R ggplot2 v0.9.3 instead of v2.1.0 . v0.9.3 contains some bug 
# which causes an issue on some plot. Expect some error message because of this.
sudo: required
dist: trusty
python:
# snakemake only works with Python3+
  #- "2.7"
  #- "3.2"
  - "3.6"
env:
  - SBPIPE=$(pwd)
# necessary for installing Python dependencies
#virtualenv:
#  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  # This is not necessary on 14.04
  #- sudo add-apt-repository ppa:texlive-backports/ppa -y
  - sudo apt-get update -q
  - sudo apt-get -y --force-yes install r-base r-base-dev
  - sudo apt-get -y --force-yes --no-install-recommends install texlive-latex-base texlive-latex-recommended
install:
  # install other dependencies
  
  # install copasi
  - wget https://github.com/copasi/COPASI/releases/download/Build-104/COPASI-4.16.104-Linux-64bit.tar.gz
  - tar xvzf COPASI-4.16.104-Linux-64bit.tar.gz
  - PATH=$PATH:$(pwd)/COPASI-4.16.104-Linux-64bit/bin/
   
  # install R dependencies
  - mkdir -p $(pwd)/r_libs/  
  - export R_LIBS_USER=$(pwd)/r_libs/
  - Rscript install_rdeps.r
  # We use pip 3
  - pip3 install -r requirements.txt
  
  # install sbpipe
  - python setup.py install
# command to run tests
script:
#  Use nosetests so that travis output depends on the return value from the test_suite
# it would be nice to run tests/test_suite.py , but even if the full name of the conf files is passed, 
# nosetest return ERROR for each test (even though these actually work correctly..)
  - cd tests
  - nosetests -v -s test_suite.py
