# This file is part of sbpipe.
#
# sbpipe is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sbpipe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with sbpipe.  If not, see <http://www.gnu.org/licenses/>.

language: python
sudo: required
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"
install:


  # install xvfb
  # we don't have X11 on Travis-CI, so we use a virtual framebuffer
  # because R packages for generating figures were compiled with X11
  # support.
  - sudo apt-get update
  - sudo apt-get install xvfb
  - PID=$$
  # create a virtual screen and suppress the output
  - Xvfb :$PID -screen 0 800x600x16 2>/dev/null 1>&2 &
  - xvfb_pid=$!
  - export DISPLAY=:$PID.0



  # install copasi
  - wget https://github.com/copasi/COPASI/releases/download/Build-166/COPASI-4.21.166-Linux-64bit.tar.gz
  - tar xvzf COPASI-4.21.166-Linux-64bit.tar.gz
  - PATH=$PATH:$(pwd)/COPASI-4.21.166-Linux-64bit/bin/



  # install miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # install conda build in order to build the conda package for SBpipe
  - conda install conda-build
  - conda config --set anaconda_upload no

  # install SBpipe
  # create the `sbpipe` environment
  - conda env create --name sbpipe --file environment.yaml
  - source activate sbpipe

  # install SBpiper
  - R -e 'install.packages("devtools"); devtools::install_github("pdp10/sbpiper")'

  # install sbpipe directly
  #- python setup.py install

  # install sbpipe using conda build (which internally runs `python setup.py install`)
  #- conda build conda_recipe/meta.yaml
  #- conda install sbpipe --use-local



  # install SBpipe (optional packages)
  # install snakemake (optional for Python 3)
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      conda install -c bioconda snakemake ;
    fi

  # install latex dependencies (optional)
  - conda install -c pkgw/label/superseded texlive-core=20160520 texlive-selected=20160715

  # install colorlog (optional)
  - conda install -c conda-forge colorlog



# command to run tests
script:
  # Override SBpipe logging configuration (we don't want it to write anything into the log file).
  - sed -i 's/level=DEBUG/level=CRITICAL/g' logging_config.ini
  - nosetests test_suite.py --nocapture --verbose

#  # To test and see SBpipe output
#  - cd tests/copasi_models
#  - sbpipe -s ir_model_det_simul.yaml

