name:
  - canc
channels:
  - conda-forge
  - bioconda
  - r
  - pkgw
  - defaults
dependencies:
  - colorlog
  - nose
  - pandas
  - pyaml
  - python
  - numpy
  - scipy
  - setuptools
  - snakemake >=3.10.1
  - r-essentials
  - r-hmisc
  - texlive-selected
