# This file is part of sbpipe.
#
# sbpipe is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sbpipe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with sbpipe.  If not, see <http://www.gnu.org/licenses/>.

name:
  - sbpipe
channels:
  - conda-forge
  - bioconda
  - r
  - pkgw
  - defaults
dependencies:
  - colorlog
  - nose
  - pandas
  - pyaml
  - python
  - numpy
  - scipy
  - setuptools
  - snakemake >=3.10.1
  - r-essentials
  - r-hmisc
  - texlive-selected
