package:
  name: sbpipe
  version: "3.13.0"

build:
  number: 1
  script: python setup.py install
  noarch_python: True

source:
  git_url: https://github.com/pdp10/sbpipe.git
  git_rev: 1.1.4

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    
test:
  requires:
    - nose

about:
  home: https://github.com/pdp10/sbpipe
