# Copyright (c) 2018 Piero Dalle Pezze
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.



# Use load_setup_py_data from conda_build.jinja_context to populate some fields
# with values fed from setuptools.

{% set data = load_setup_py_data() %}

package:
  name: sbpipe
  version: {{ data.get('version') }}

about:
  summary: Pipelines for systems modelling of biological networks
  home: http://sbpipe.readthedocs.io
  license: MIT
  license_file: LICENSE

extra:
  maintainers:
   - Piero Dalle Pezze

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
  #string: py_{{ environ.get("PY_VER") }}_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  entry_points:
    - sbpipe = sbpipe.__main__:main
    - sbpipe_move_datasets = sbpipe.sbpipe_move_datasets:main

source:
  # conda-build is also executed by travis, we use the local source, rather
  # than cloning from github here.
  #git_tag: master
  #git_url: https://github.com/pdp10/sbpipe.git
  path: ../

requirements:
  build:
    - setuptools
    - python
    - pyyaml
    - colorlog
  run:
    - python
    - pyyaml
    - colorlog
    - sbpiper 1.8.*
    - python-copasi   # -c fbergmann
#    - snakemake       # -c bioconda

#test:
#  requires:
#    - nose
#  run:
#    - tests/test_suite.py
