# Copyright (c) 2018 Piero Dalle Pezze
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#######
# NOTE:
#
# (1) The meta.yaml files of sbpipe and sbpiper for the bioconda channel are located here:
# https://github.com/bioconda/bioconda-recipes
#
# (2) This meta.yaml file is used for building the SBpipe conda package by Travis-CI.
#######

# Use load_setup_py_data from conda_build.jinja_context to populate some fields
# with values fed from setuptools.
{% set data = load_setup_py_data() %}

package:
  name: sbpipe
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - sbpipe = sbpipe:main
    - sbpipe_move_datasets = sbpipe.sbpipe_move_datasets:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyyaml
    - colorlog
    - sbpiper 1.8.*
    - python-copasi

test:
  imports:
    - sbpipe
  commands:
    - sbpipe --help
    - sbpipe_move_datasets --help

about:
  home: http://sbpipe.readthedocs.io
  license: MIT
  summary: SBpipe is a collection of pipelines for systems modelling of biological networks. It allows mathematical modellers to automatically repeat the tasks of model simulation and parameter estimation, and extract robustness information from these repeat sequences in a solid and consistent manner, facilitating model development and analysis. SBpipe can run models implemented in COPASI, Python or coded in any other programming language using Python as a wrapper module. Pipelines can run on multicore computers, Sun Grid Engine (SGE), Load Sharing Facility (LSF) clusters, or via Snakemake.

extra:
  recipe-maintainers: 'Piero Dalle Pezze'
  identifiers:
    - doi:10.1186/s12918-017-0423-3
