# This file is part of sbpipe.
#
# sbpipe is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sbpipe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with sbpipe.  If not, see <http://www.gnu.org/licenses/>.



# Use load_setup_py_data from conda_build.jinja_context to populate some fields
# with values fed from setuptools.

{% set data = load_setup_py_data() %}

package:
  name: sbpipe
  version: {{ data.get('version') }}

about:
  summary: Pipelines for systems modelling of biological networks
  home: http://sbpipe.readthedocs.io
  license: LGPL-3.0
  license_file: LICENSE

extra:
  maintainers:
   - Piero Dalle Pezze

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
  #string: py_{{ environ.get("PY_VER") }}_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  entry_points:
    - sbpipe = sbpipe.__main__:main
    - sbpipe_move_datasets = sbpipe.sbpipe_move_datasets:main

source:
  # conda-build is also executed by travis, we use the local source, rather
  # than cloning from github here.
  #git_tag: master
  #git_url: https://github.com/pdp10/sbpipe.git
  path: ../

requirements:
  build:
    - setuptools
    - python
    - pyyaml
    - colorlog
  run:
    - python
    - pyyaml
    - colorlog
    - sbpiper 1.7.*
    - python-copasi   # -c fbergmann
#    - snakemake       # -c bioconda

#test:
#  requires:
#    - nose
#  run:
#    - tests/test_suite.py
