package:
  name: sbpipe
  version: "3.13.0"

build:
  number: 1
  script: python setup.py install
  noarch_python: True

source:
  git_url: https://github.com/pdp10/sbpipe.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    
test:
  requires:
    - nose

about:
  summary: Pipelines for systems modelling of biological networks
  home: https://github.com/pdp10/sbpipe
  license: GNU LGPL v3
  license_file: ../LICENSE
